// adapters/claude.ts — Claude Code writes its own bookkeeping into the
// transcript as user turns: the local-command caveat, a slash command's
// name/message/args, and that command's stdout. Rendered as purple bubbles
// they read as if the user had typed them.

import { test } from "node:test"
import assert from "node:assert/strict"
import { foldResults, isLocalCommandWrapper, toolTitle } from "../src/harnesses/claude.ts"
import type { Part } from "../src/core/types.ts"

test("claude's local-command bookkeeping is recognised", () => {
  assert.equal(isLocalCommandWrapper("<local-command-caveat>the messages below were generated by the user while running local commands</local-command-caveat>"), true)
  assert.equal(
    isLocalCommandWrapper("<command-name>/export</command-name>\n<command-message>export</command-message>\n<command-args></command-args>"),
    true,
  )
  assert.equal(isLocalCommandWrapper("<local-command-stdout>Conversation exported to: /tmp/x.jsonl</local-command-stdout>"), true)
  assert.equal(isLocalCommandWrapper([{ type: "text", text: "<command-name>/export</command-name>" }]), true)
})

test("a real message is not mistaken for bookkeeping", () => {
  assert.equal(isLocalCommandWrapper("hello"), false)
  assert.equal(isLocalCommandWrapper("what does <command-name> do here?"), false)
  assert.equal(isLocalCommandWrapper("<command-name>/export</command-name>\nand then explain the parser"), false)
  assert.equal(isLocalCommandWrapper(""), false)
})

// A tool call the phone can read: Claude Code, unlike opencode, hands us no
// display hint, so the row said "Ran a command" with a blank line under it.
test("a tool call is titled by whatever identifies it", () => {
  assert.equal(toolTitle({ command: "git status", description: "Check status" }), "git status", "a Bash call is its command, not its description")
  assert.equal(toolTitle({ file_path: "/a/b/c.ts", old_string: "x", new_string: "y" }), "/a/b/c.ts")
  assert.equal(toolTitle({ pattern: "TODO", path: "src" }), "TODO", "a search is what it looked for, not where")
  assert.equal(toolTitle({ description: "Hunt the bug", prompt: "a very long prompt" }), "Hunt the bug", "a Task is its description, not its prompt")
  assert.equal(toolTitle({ url: "https://example.com" }), "https://example.com")
})

test("a title that identifies nothing stays absent, and a huge one is cut", () => {
  assert.equal(toolTitle({ todos: [{ content: "x" }] }), undefined, "no string worth showing")
  assert.equal(toolTitle(undefined), undefined)
  assert.equal(toolTitle("not an object"), undefined)
  assert.equal(toolTitle({ command: "   " }), undefined, "whitespace is not a title")
  const long = toolTitle({ prompt: "x".repeat(500) })!
  assert.equal(long.length, 201, "capped, with an ellipsis to show it was cut")
  assert.ok(long.endsWith("…"))
})

// The bug the phone showed as an empty purple bubble after every single tool
// call: a tool's output comes back as a *user* turn, so each one became a
// message of its own with nothing in it to render.
test("a tool result folds onto its call instead of becoming a message", () => {
  const call: Part & { kind: "tool" } = { kind: "tool", id: "t1", name: "Bash", input: {}, output: "", status: "completed" }
  const index = new Map<string, Part & { kind: "tool" }>([["t1", call]])
  const left = foldResults([{ kind: "tool", id: "t1", name: "result", input: {}, output: "hello", status: "completed" }], index)
  assert.deepEqual(left, [], "nothing is left to render — the turn was only a result")
  assert.equal(call.output, "hello", "the output landed on the call")
})

test("a failed result marks its call failed", () => {
  const call: Part & { kind: "tool" } = { kind: "tool", id: "t1", name: "Bash", input: {}, output: "", status: "completed" }
  const index = new Map<string, Part & { kind: "tool" }>([["t1", call]])
  foldResults([{ kind: "tool", id: "t1", name: "result", input: {}, output: "boom", status: "error" }], index)
  assert.equal(call.status, "error")
})

test("a result with no call to fold onto is dropped, not shown as a stray row", () => {
  const left = foldResults([{ kind: "tool", id: "gone", name: "result", input: {}, output: "x", status: "completed" }], new Map())
  assert.deepEqual(left, [], "a truncated transcript must not sprout a nameless 'result' row")
})

test("real content survives the fold untouched", () => {
  const call: Part & { kind: "tool" } = { kind: "tool", id: "t1", name: "Bash", input: {}, output: "", status: "completed" }
  const parts: Part[] = [{ kind: "text", text: "on it" }, call]
  assert.deepEqual(foldResults(parts, new Map()), parts)
})
