// adapters/claude.ts — Claude Code writes its own bookkeeping into the
// transcript as user turns: the local-command caveat, a slash command's
// name/message/args, and that command's stdout. Rendered as purple bubbles
// they read as if the user had typed them.

import { test } from "node:test"
import assert from "node:assert/strict"
import { isLocalCommandWrapper } from "../src/adapters/claude.ts"

test("claude's local-command bookkeeping is recognised", () => {
  assert.equal(isLocalCommandWrapper("<local-command-caveat>the messages below were generated by the user while running local commands</local-command-caveat>"), true)
  assert.equal(
    isLocalCommandWrapper("<command-name>/export</command-name>\n<command-message>export</command-message>\n<command-args></command-args>"),
    true,
  )
  assert.equal(isLocalCommandWrapper("<local-command-stdout>Conversation exported to: /tmp/x.jsonl</local-command-stdout>"), true)
  assert.equal(isLocalCommandWrapper([{ type: "text", text: "<command-name>/export</command-name>" }]), true)
})

test("a real message is not mistaken for bookkeeping", () => {
  assert.equal(isLocalCommandWrapper("hello"), false)
  assert.equal(isLocalCommandWrapper("what does <command-name> do here?"), false)
  assert.equal(isLocalCommandWrapper("<command-name>/export</command-name>\nand then explain the parser"), false)
  assert.equal(isLocalCommandWrapper(""), false)
})
