package dev.jep.client.presentation.theme

// GENERATED by scripts/gen_icon.py — edit the source bezier there.
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.addPathNodes
import androidx.compose.ui.unit.dp

private const val MARK_BODY = "M 12.00,9.29 C 13.85,7.39 18.02,7.09 19.64,9.56 C 21.14,11.93 20.33,15.67 18.02,17.94 C 16.51,19.42 14.78,19.92 13.50,19.23 C 12.58,18.83 11.42,18.83 10.50,19.23 C 9.22,19.92 7.49,19.42 5.98,17.94 C 3.67,15.67 2.86,11.93 4.36,9.56 C 5.98,7.09 10.15,7.39 12.00,9.29 Z"
private const val MARK_LEAF = "M 13.39,6.99 C 14.20,5.02 16.51,4.23 18.02,4.53 C 17.32,6.20 15.47,7.29 13.39,6.99 Z"

val JepMark: ImageVector = ImageVector.Builder(
    name = "JepMark",
    defaultWidth = 24.dp,
    defaultHeight = 24.dp,
    viewportWidth = 24f,
    viewportHeight = 24f,
).apply {
    val paint = Brush.linearGradient(
        0f to Color(0xFFF66676),
        0.45f to Color(0xFFE43A50),
        1f to Color(0xFFC42438),
        start = Offset(0f, 4.47f),
        end = Offset(0f, 19.53f),
    )
    addPath(addPathNodes(MARK_BODY), fill = paint)
    addPath(addPathNodes(MARK_LEAF), fill = paint)
    addPath(
        addPathNodes("M 12.17,8.67 L 12.52,5.40"),
        stroke = SolidColor(Color(0xFFE95A6E)),
        strokeLineWidth = 1.15f,
        strokeLineCap = StrokeCap.Round,
    )
}.build()
